window.YID = {
  CONJUGATION_BANK: [
    { id:1, sourcePage:84, infinitive:"לערנען", presentSentence:"איך לערן אין אוניווערסיטעט",
      translation:"אני לומד באוניברסיטה", past:"איך האָב געלערנט אין אוניווערסיטעט",
      future:"איך וועל לערנען אין אוניווערסיטעט", imperative:"לערן! לערנט!",
      negative:"איך לערן נישט אין אוניווערסיטעט",
      positiveQuestion:"צי לערן איך אין אוניווערסיטעט?",
      negativeQuestion:"לערן איך אין אוניווערסיטעט?",
      tags:["regular","hobn"], explanation:"פועל רגיל, עזר האָבן, עבר געלערנט.", needsReview:false, reviewNote:"" },
    { id:2, sourcePage:84, infinitive:"גיין", presentSentence:"דו גייסט מיט די קינדער אַהײַם",
      translation:"אתה הולך עם הילדים הביתה", past:"דו ביסט געגאַנגען מיט די קינדער אַהײַם",
      future:"דו וועסט גיין מיט די קינדער אַהײַם", imperative:"גיי! גייט!",
      negative:"דו גייסט נישט מיט די קינדער אַהײַם",
      positiveQuestion:"צי גייסטו מיט די קינדער אַהײַם?",
      negativeQuestion:"גייסטו מיט די קינדער אַהײַם?",
      tags:["motion","zayn","irregular_past"], explanation:"תנועה → עזר זײַן. עבר חריג: געגאַנגען. מיר/זיי גייען.", needsReview:false, reviewNote:"" },
    { id:3, sourcePage:84, infinitive:"שרײַבן", presentSentence:"ער שרײַבט אַ בריוו צו זײַן קוזין",
      translation:"הוא כותב מכתב לבן דודו", past:"ער האָט געשריבן אַ בריוו צו זײַן קוזין",
      future:"ער וועט שרײַבן אַ בריוו צו זײַן קוזין", imperative:"שרײַב! שרײַבט!",
      negative:"ער שרײַבט נישט קיין בריוו צו זײַן קוזין",
      positiveQuestion:"צי שרײַבט ער אַ בריוו צו זײַן קוזין?",
      negativeQuestion:"שרײַבט ער אַ בריוו צו זײַן קוזין?",
      tags:["hobn","irregular_past","nisht_keyn"], explanation:"עבר חריג: געשריבן (י' יורדת, בלי ט). שלילה: אַ בריוו לא מיודע → נישט קיין.", needsReview:false, reviewNote:"" },
    { id:4, sourcePage:84, infinitive:"זײַן", presentSentence:"זי איז די שענסטע אין קלאַס",
      translation:"היא הכי יפה בכיתה", past:"זי איז געווען די שענסטע אין קלאָס",
      future:"זי וועט זײַן די שענסטע אין קלאָס", imperative:"זײַ! זײַט!",
      negative:"זי איז נישט די שענסטע אין קלאַס",
      positiveQuestion:"צי איז זי די שענסטע אין קלאָס?",
      negativeQuestion:"איז זי די שענסטע אין קלאָס?",
      tags:["zayn","irregular_past"], explanation:"זײַן: עבר געווען. שלילה בלי קיין כי 'די שענסטע' מיודע.", needsReview:false, reviewNote:"" },
    { id:5, sourcePage:84, infinitive:"האָבן", presentSentence:"מיר האָבן דרײַ קינדער",
      translation:"יש לנו שלושה ילדים", past:"מיר האָבן געהאַט דרײַ קינדער",
      future:"מיר וועלן האָבן דרײַ קינדער", imperative:"האָב! האָט!",
      negative:"מיר האָבן נישט קיין דרײַ קינדער",
      positiveQuestion:"צי האָבן מיר דרײַ קינדער?",
      negativeQuestion:"האָבן מיר דרײַ קינדער?",
      tags:["hobn","nisht_keyn"], explanation:"האָבן: עבר געהאַט. מספר (דרײַ) → נישט קיין.", needsReview:false, reviewNote:"" },
    { id:6, sourcePage:84, infinitive:"לויפֿן", presentSentence:"איר לויפֿט קויפֿן גוטע זאַכן",
      translation:"אתם רצים לקנות דברים טובים", past:"איר זײַט געלאָפֿן קויפֿן גוטע זאַכן",
      future:"איר וועט לויפֿן קויפֿן גוטע זאַכן", imperative:"לויף! לויפֿט!",
      negative:"איר לויפֿט נישט קויפֿן קיין גוטע זאַכן",
      positiveQuestion:"צי לויפֿט איר קויפֿן גוטע זאַכן?",
      negativeQuestion:"לויפֿט איר קויפֿן גוטע זאַכן?",
      tags:["motion","zayn","irregular_past","nisht_keyn"], explanation:"לרוץ = כל הגוף → זײַן. עבר געלאָפֿן.", needsReview:false, reviewNote:"" },
    { id:7, sourcePage:84, infinitive:"מאַכן", presentSentence:"זיי מאַכן די היים-אַרבעט",
      translation:"הם עושים את עבודת הבית", past:"זיי האָבן געמאַכט די היים-אַרבעט",
      future:"זיי וועלן מאַכן די היים-אַרבעט", imperative:"מאַך! מאַכט!",
      negative:"זיי מאַכן נישט די היים-אַרבעט",
      positiveQuestion:"צי מאַכן זיי די היים-אַרבעט?",
      negativeQuestion:"מאַכן זיי די היים-אַרבעט?",
      tags:["regular","hobn"], explanation:"רגיל, עזר האָבן, עבר געמאַכט. 'די היים-אַרבעט' מיודע → בלי קיין.", needsReview:false, reviewNote:"" },
    { id:8, sourcePage:84, infinitive:"קוקן", presentSentence:"דער חבר קוקט אויף אַ שיינעם פֿילם",
      translation:"החבר מסתכל על סרט יפה", past:"דער חבר האָט געקוקט אויף אַ שיינעם פֿילם",
      future:"דער חבר וועט קוקן אויף אַ שיינעם פֿילם", imperative:"קוק! קוקט!",
      negative:"דער חבר קוקט נישט אויף קיין שיינעם פֿילם",
      positiveQuestion:"צי קוקט דער חבר אויף אַ שיינעם פֿילם?",
      negativeQuestion:"קוקט דער חבר אויף אַ שיינעם פֿילם?",
      tags:["regular","hobn","nisht_keyn"], explanation:"רגיל, עבר געקוקט. קיין אחרי מילת יחס: אויף קיין.", needsReview:false, reviewNote:"" },
    { id:9, sourcePage:84, infinitive:"נעמען", presentSentence:"די חברטע נעמט אַ בוך",
      translation:"החברה לוקחת ספר", past:"די חברטע האָט גענומען אַ בוך",
      future:"די חברטע וועט נעמען אַ בוך", imperative:"נעם! נעמט!",
      negative:"די חברטע נעמט נישט קיין בוך",
      positiveQuestion:"צי נעמט די חברטע אַ בוך?",
      negativeQuestion:"נעמט די חברטע אַ בוך?",
      tags:["hobn","irregular_past","nisht_keyn"], explanation:"עבר חריג: גענומען. אַ בוך → נישט קיין.", needsReview:false, reviewNote:"" },
    { id:10, sourcePage:84, infinitive:"אַרבעטן", presentSentence:"די לערערס אַרבעטן מיט אַ סך תלמידים",
      translation:"המורים עובדים עם הרבה תלמידים", past:"די לערערס האָבן געאַרבעט מיט אַ סך תלמידים",
      future:"די לערערס וועלן אַרבעטן מיט אַ סך תלמידים", imperative:"אַרבעט! אַרבעט!",
      negative:"די לערערס אַרבעטן נישט מיט קיין סך תלמידים",
      positiveQuestion:"צי אַרבעטן די לערערס מיט אַ סך תלמידים?",
      negativeQuestion:"אַרבעטן די לערערס מיט אַ סך תלמידים?",
      tags:["regular","hobn","no_double_t"], explanation:"מסתיים ב-ט → בלי טט: געאַרבעט. ציווי יחיד=רבים (אַרבעט).", needsReview:false, reviewNote:"" },
    { id:11, sourcePage:84, infinitive:"רעדן", presentSentence:"איך רעד מיט חברים אין פּאַרק",
      translation:"אני מדבר עם חברים בפארק", past:"איך האָב גערעדט מיט חברים אין פּאַרק",
      future:"איך וועל רעדן מיט חברים אין פּאַרק", imperative:"רעד! רעדט!",
      negative:"איך רעד נישט מיט קיין חברים אין קיין פּאַרק",
      positiveQuestion:"צי רעד איך מיט חברים אין פּאַרק?",
      negativeQuestion:"רעד איך מיט חברים אין פּאַרק?",
      tags:["regular","hobn","nisht_keyn"], explanation:"רגיל, עבר גערעדט. שלילה: חברים לא מיודע → נישט קיין.", needsReview:false, reviewNote:"" },
    { id:12, sourcePage:84, infinitive:"קומען", presentSentence:"דו קומסט אַהיים זייער שפּעט אין אָוונט",
      translation:"אתה בא הביתה מאוד מאוחר בערב", past:"דו ביסט געקומען אַהיים זייער שפּעט אין אָוונט",
      future:"דו וועסט קומען אַהיים זייער שפּעט אין אָוונט", imperative:"קום! קומט!",
      negative:"דו קומסט נישט אַהיים זייער שפּעט אין אָוונט",
      positiveQuestion:"צי קומסטו אַהיים זייער שפּעט אין אָוונט?",
      negativeQuestion:"קומסטו אַהיים זייער שפּעט אין אָוונט?",
      tags:["motion","zayn","irregular_past"], explanation:"תנועה → זײַן. עבר חריג: געקומען. שאלה: קומסט+דו→קומסטו.", needsReview:false, reviewNote:"" },
    { id:13, sourcePage:84, infinitive:"לערנען", presentSentence:"ער לערנט דרײַ נײַע לעקציעס",
      translation:"הוא לומד שלושה שיעורים חדשים", past:"ער האָט געלערנט דרײַ נײַע לעקציעס",
      future:"ער וועט לערנען דרײַ נײַע לעקציעס", imperative:"לערן! לערנט!",
      negative:"ער לערנט נישט קיין דרײַ נײַע לעקציעס",
      positiveQuestion:"צי לערנט ער דרײַ נײַע לעקציעס?",
      negativeQuestion:"לערנט ער דרײַ נײַע לעקציעס?",
      tags:["regular","hobn","nisht_keyn"], explanation:"רגיל, עבר געלערנט. מספר → נישט קיין.", needsReview:false, reviewNote:"" },
    { id:14, sourcePage:84, infinitive:"וואַרטן", presentSentence:"זי וואַרט אַ לאַנגע צײַט",
      translation:"היא מחכה זמן רב", past:"זי האָט געוואַרט אַ לאַנגע צײַט",
      future:"זי וועט וואַרטן אַ לאַנגע צײַט", imperative:"וואַרט! וואַרט!",
      negative:"זי וואַרט נישט קיין לאַנגע צײַט",
      positiveQuestion:"צי וואַרט זי אַ לאַנגע צײַט?",
      negativeQuestion:"וואַרט זי אַ לאַנגע צײַט?",
      tags:["regular","hobn","no_double_t"], explanation:"מסתיים ב-ט → בלי טט: געוואַרט. ציווי יחיד=רבים.", needsReview:false, reviewNote:"" },
    { id:15, sourcePage:84, infinitive:"פֿאָרן", presentSentence:"די חברים פֿאָרן אויף אַ וויזיט קיין חיפה",
      translation:"החברים נוסעים לביקור בחיפה", past:"די חברים זײַנען געפֿאָרן אויף אַ וויזיט קיין חיפה",
      future:"די חברים וועלן פֿאָרן אויף אַ וויזיט קיין חיפה", imperative:"פֿאָר! פֿאָרט!",
      negative:"די חברים פֿאָרן נישט אויף קיין וויזיט קיין חיפה",
      positiveQuestion:"צי פֿאָרן די חברים אויף אַ וויזיט קיין חיפה?",
      negativeQuestion:"פֿאָרן די חברים אויף אַ וויזיט קיין חיפה?",
      tags:["motion","zayn","irregular_past"], explanation:"לנסוע = כל הגוף → זײַן. עבר געפֿאָרן.", needsReview:false, reviewNote:"" },
    { id:16, sourcePage:84, infinitive:"אַרויספֿאָרן", presentSentence:"די עלטערן פֿאָרן אַרויס אויף אַ וואַקאַציע",
      translation:"ההורים יוצאים לחופשה", past:"די עלטערן זײַנען אַרויסגעפֿאָרן אויף אַ וואַקאַציע",
      future:"די עלטערן וועלן אַרויספֿאָרן אויף אַ וואַקאַציע", imperative:"פֿאָר אַרויס! פֿאָרט אַרויס!",
      negative:"די עלטערן פֿאָרן נישט אַרויס אויף קיין וואַקאַציע",
      positiveQuestion:"צי פֿאָרן די עלטערן אַרויס אויף אַ וואַקאַציע?",
      negativeQuestion:"פֿאָרן די עלטערן אַרויס אויף אַ וואַקאַציע?",
      tags:["prefix_split","motion","zayn","irregular_past"], explanation:"מתפרק (אַרויס) — מתפרק בהווה ובציווי. עבר עם זײַן: אַרויסגעפֿאָרן (גע באמצע).", needsReview:false, reviewNote:"" },
    { id:17, sourcePage:84, infinitive:"אַרײַנגיין", presentSentence:"מיר גייען אַרײַן אין דעם גרויסן פּאַרק",
      translation:"אנחנו נכנסים לפארק הגדול", past:"מיר זײַנען אַרײַנגעגאַנגען אין דעם גרויסן פּאַרק",
      future:"מיר וועלן אַרײַנגיין אין דעם גרויסן פּאַרק", imperative:"גיי אַרײַן! גייט אַרײַן!",
      negative:"מיר גייען נישט אַרײַן אין דעם גרויסן פּאַרק",
      positiveQuestion:"צי גייען מיר אַרײַן אין דעם גרויסן פּאַרק?",
      negativeQuestion:"גייען מיר אַרײַן אין דעם גרויסן פּאַרק?",
      tags:["prefix_split","motion","zayn","irregular_past"], explanation:"מתפרק (אַרײַן). עבר עם זײַן: אַרײַנגעגאַנגען. מיר/זיי גייען.", needsReview:false, reviewNote:"" },
    { id:18, sourcePage:84, infinitive:"אָפּרעדן", presentSentence:"איר רעדט אָפּ מיט חברים",
      translation:"אתם מסכמים עם חברים", past:"איר האָט אָפּגערעדט מיט חברים",
      future:"איר וועט אָפּרעדן מיט חברים", imperative:"רעד אָפּ! רעדט אָפּ!",
      negative:"איר רעדט נישט אָפּ מיט קיין חברים",
      positiveQuestion:"צי רעדט איר אָפּ מיט חברים?",
      negativeQuestion:"רעדט איר אָפּ מיט חברים?",
      tags:["prefix_split","hobn","nisht_keyn"], explanation:"מתפרק (אָפּ), עזר האָבן, עבר אָפּגערעדט. חברים לא מיודע → נישט קיין.", needsReview:false, reviewNote:"" },
    { id:19, sourcePage:84, infinitive:"אָפּקויפֿן", presentSentence:"זיי קויפֿן אָפּ די נײַע ביכער",
      translation:"הם קונים / משלימים את קניית הספרים החדשים", past:"זיי האָבן אָפּגעקויפֿט די נײַע ביכער",
      future:"זיי וועלן אָפּקויפֿן די נײַע ביכער", imperative:"קויף אָפּ! קויפֿט אָפּ!",
      negative:"זיי קויפֿן נישט אָפּ די נײַע ביכער",
      positiveQuestion:"צי קויפֿן זיי אָפּ די נײַע ביכער?",
      negativeQuestion:"קויפֿן זיי אָפּ די נײַע ביכער?",
      tags:["prefix_split","hobn"], explanation:"מתפרק (אָפּ). עבר אָפּגעקויפֿט (גע באמצע). 'די נײַע ביכער' מיודע → בלי קיין.", needsReview:false, reviewNote:"" },
    { id:20, sourcePage:84, infinitive:"אויסלייענען", presentSentence:"דער חבר לייענט אויס אַן אַרטיקל",
      translation:"החבר קורא מאמר", past:"דער חבר האָט אויסגעלייענט אַן אַרטיקל",
      future:"דער חבר וועט אויסלייענען אַן אַרטיקל", imperative:"לייען אויס! לייענט אויס!",
      negative:"דער חבר לייענט נישט אויס קיין אַרטיקל",
      positiveQuestion:"צי לייענט דער חבר אויס אַן אַרטיקל?",
      negativeQuestion:"לייענט דער חבר אויס אַן אַרטיקל?",
      tags:["prefix_split","hobn","nisht_keyn"], explanation:"מתפרק (אויס). אַן אַרטיקל לא מיודע → נישט קיין. עבר אויסגעלייענט.", needsReview:false, reviewNote:"" },
    { id:21, sourcePage:84, infinitive:"באַשרײַבן", presentSentence:"איך באַשרײַב מײַן לעבן אין אַ בוך",
      translation:"אני מתאר את חיי בספר", past:"איך האָב באַשריבן מײַן לעבן אין אַ בוך",
      future:"איך וועל באַשרײַבן מײַן לעבן אין אַ בוך", imperative:"באַשרײַב! באַשרײַבט!",
      negative:"איך באַשרײַב נישט מײַן לעבן אין קיין בוך",
      positiveQuestion:"צי באַשרײַב איך מײַן לעבן אין אַ בוך?",
      negativeQuestion:"באַשרײַב איך מײַן לעבן אין אַ בוך?",
      tags:["prefix_fixed","hobn","irregular_past"], explanation:"בלתי מתפרק (באַ) → בלי גע. שורש שרײַבן חריג → באַשריבן.", needsReview:false, reviewNote:"" },
    { id:22, sourcePage:84, infinitive:"אָפּקויפֿן", presentSentence:"דו קויפֿסט אָפּ די מאַשין",
      translation:"אתה משלים את קניית המכונית", past:"דו האָסט אָפּגעקויפֿט די מאַשין",
      future:"דו וועסט אָפּקויפֿן די מאַשין", imperative:"קויף אָפּ! קויפֿט אָפּ!",
      negative:"דו קויפֿסט נישט אָפּ די מאַשין",
      positiveQuestion:"צי קויפֿסטו אָפּ די מאַשין?",
      negativeQuestion:"קויפֿסטו אָפּ די מאַשין?",
      tags:["prefix_split","hobn"], explanation:"מתפרק. קויפֿן לא צריך כל הגוף → האָבן, עבר אָפּגעקויפֿט.", needsReview:false, reviewNote:"" },
    { id:23, sourcePage:84, infinitive:"פֿאַרקויפֿן", presentSentence:"ער פֿאַרקויפֿט זײַן שטוב",
      translation:"הוא מוכר את ביתו", past:"ער האָט פֿאַרקויפֿט זײַן שטוב",
      future:"ער וועט פֿאַרקויפֿן זײַן שטוב", imperative:"פֿאַרקויף! פֿאַרקויפֿט!",
      negative:"ער פֿאַרקויפֿט נישט זײַן שטוב",
      positiveQuestion:"צי פֿאַרקויפֿט ער זײַן שטוב?",
      negativeQuestion:"פֿאַרקויפֿט ער זײַן שטוב?",
      tags:["prefix_fixed","hobn"], explanation:"בלתי מתפרק (פֿאַר) → בלי גע: פֿאַרקויפֿט. 'זײַן שטוב' מיודע → בלי קיין.", needsReview:false, reviewNote:"" },
    { id:24, sourcePage:84, infinitive:"באַלערנען", presentSentence:"זי באַלערנט אירע קינדער",
      translation:"היא מחנכת את ילדיה", past:"זי האָט באַלערנט אירע קינדער",
      future:"זי וועט באַלערנען אירע קינדער", imperative:"באַלערן! באַלערנט!",
      negative:"זי באַלערנט נישט אירע קינדער",
      positiveQuestion:"צי באַלערנט זי אירע קינדער?",
      negativeQuestion:"באַלערנט זי אירע קינדער?",
      tags:["prefix_fixed","hobn"], explanation:"בלתי מתפרק (באַ) → בלי גע: באַלערנט. עזר האָבן.", needsReview:false, reviewNote:"" },
    { id:25, sourcePage:84, infinitive:"אַרויסלויפֿן", presentSentence:"מיר לויפֿן אַרויס פֿון צימער",
      translation:"אנחנו רצים החוצה מהחדר", past:"מיר זײַנען אַרויסגעלאָפֿן פֿון צימער",
      future:"מיר וועלן אַרויסלויפֿן פֿון צימער", imperative:"לויף אַרויס! לויפֿט אַרויס!",
      negative:"מיר לויפֿן נישט אַרויס פֿון קיין צימער",
      positiveQuestion:"צי לויפֿן מיר אַרויס פֿון צימער?",
      negativeQuestion:"לויפֿן מיר אַרויס פֿון צימער?",
      tags:["prefix_split","motion","zayn","irregular_past"], explanation:"מתפרק (אַרויס) + לויפֿן תנועה → זײַן. עבר אַרויסגעלאָפֿן.", needsReview:false, reviewNote:"" },
    { id:26, sourcePage:84, infinitive:"פֿאַרמאַכן", presentSentence:"איר פֿאַרמאַכט די טיר מיט אַ גרויסן רעש",
      translation:"אתם סוגרים את הדלת ברעש גדול", past:"איר האָט פֿאַרמאַכט די טיר מיט אַ גרויסן רעש",
      future:"איר וועט פֿאַרמאַכן די טיר מיט אַ גרויסן רעש", imperative:"פֿאַרמאַך! פֿאַרמאַכט!",
      negative:"איר פֿאַרמאַכט נישט די טיר מיט קיין גרויסן רעש",
      positiveQuestion:"צי פֿאַרמאַכט איר די טיר מיט אַ גרויסן רעש?",
      negativeQuestion:"פֿאַרמאַכט איר די טיר מיט אַ גרויסן רעש?",
      tags:["prefix_fixed","hobn"], explanation:"בלתי מתפרק → בלי גע. עבר פֿאַרמאַכט. כתיב אחיד: פֿאַרמאַכן.", needsReview:false, reviewNote:"" },
    { id:27, sourcePage:84, infinitive:"מיטגיין", presentSentence:"זיי גייען מיט מיט די קינדער",
      translation:"הם מצטרפים אל הילדים", past:"זיי זײַנען מיטגעגאַנגען מיט די קינדער",
      future:"זיי וועלן מיטגיין מיט די קינדער", imperative:"גיי מיט! גייט מיט!",
      negative:"זיי גייען נישט מיט מיט די קינדער",
      positiveQuestion:"צי גייען זיי מיט מיט די קינדער?",
      negativeQuestion:"גייען זיי מיט מיט די קינדער?",
      tags:["prefix_split","motion","zayn","irregular_past"], explanation:"מתפרק (מיט) — לכן 'מיט מיט' פעמיים תקין. עבר מיטגעגאַנגען.", needsReview:false, reviewNote:"" },
    { id:28, sourcePage:84, infinitive:"נאָכלויפֿן", presentSentence:"איך לויף נאָך נאָך אַ טעקסי",
      translation:"אני רודף אחרי מונית", past:"איך בין נאָכגעלאָפֿן נאָך אַ טעקסי",
      future:"איך וועל נאָכלויפֿן נאָך אַ טעקסי", imperative:"לויף נאָך! לויפֿט נאָך!",
      negative:"איך לויף נישט נאָך נאָך קיין טעקסי",
      positiveQuestion:"צי לויף איך נאָך נאָך אַ טעקסי?",
      negativeQuestion:"לויף איך נאָך נאָך אַ טעקסי?",
      tags:["prefix_split","motion","zayn","irregular_past"], explanation:"מתפרק (נאָך) — 'נאָך נאָך' תקין. עבר נאָכגעלאָפֿן, עזר זײַן.", needsReview:false, reviewNote:"" },
    { id:29, sourcePage:84, infinitive:"צוקומען", presentSentence:"דו קומסט צו צו די שכנים",
      translation:"אתה ניגש אל השכנים", past:"דו ביסט צוגעקומען צו די שכנים",
      future:"דו וועסט צוקומען צו די שכנים", imperative:"קום צו! קומט צו!",
      negative:"דו קומסט נישט צו צו די שכנים",
      positiveQuestion:"צי קומסטו צו צו די שכנים?",
      negativeQuestion:"קומסטו צו צו די שכנים?",
      tags:["prefix_split","motion","zayn","irregular_past"], explanation:"מתפרק (צו) — 'צו צו' תקין. עבר צוגעקומען.", needsReview:false, reviewNote:"" },
    { id:30, sourcePage:84, infinitive:"בײַפֿליען", presentSentence:"דאָס פֿייגעלע פֿליט בײַ בײַ מײַן פֿענצטער",
      translation:"הציפור מתעופפת על־יד חלוני", past:"דאָס פֿייגעלע איז בײַגעפֿלויגן בײַ מײַן פֿענצטער",
      future:"דאָס פֿייגעלע וועט בײַפֿליען בײַ מײַן פֿענצטער", imperative:"פֿלי בײַ! פֿליט בײַ!",
      negative:"דאָס פֿייגעלע פֿליט נישט בײַ בײַ מײַן פֿענצטער",
      positiveQuestion:"צי פֿליט דאָס פֿייגעלע בײַ בײַ מײַן פֿענצטער?",
      negativeQuestion:"פֿליט דאָס פֿייגעלע בײַ בײַ מײַן פֿענצטער?",
      tags:["prefix_split","motion","zayn","irregular_past"], explanation:"מתפרק (בײַ) — 'בײַ בײַ' תקין. עבר בײַגעפֿלויגן.", needsReview:false, reviewNote:"" },
    { id:31, sourcePage:84, infinitive:"האָבן מורא", presentSentence:"ער האָט מורא פֿון אַ קאַץ",
      translation:"הוא פוחד מחתולה", past:"ער האָט געהאַט מורא פֿון אַ קאַץ",
      future:"ער וועט האָבן מורא פֿון אַ קאַץ", imperative:"האָב מורא! האָט מורא!",
      negative:"ער האָט נישט מורא פֿון קיין קאַץ",
      positiveQuestion:"צי האָט ער מורא פֿון אַ קאַץ?",
      negativeQuestion:"האָט ער מורא פֿון אַ קאַץ?",
      tags:["helper_expr","hobn","nisht_keyn"], explanation:"ביטוי עזר — רק האָבן מוטה (מורא לא). עבר געהאַט מורא. קיין אחרי פֿון.", needsReview:false, reviewNote:"" },
    { id:32, sourcePage:84, infinitive:"זײַן שולדיק", presentSentence:"זי איז שולדיק אין דער מעשה",
      translation:"היא אשמה במעשה", past:"זי איז געווען שולדיק אין דער מעשה",
      future:"זי וועט זײַן שולדיק אין דער מעשה", imperative:"זײַ שולדיק! זײַט שולדיק!",
      negative:"זי איז נישט שולדיק אין דער מעשה",
      positiveQuestion:"צי איז זי שולדיק אין דער מעשה?",
      negativeQuestion:"איז זי שולדיק אין דער מעשה?",
      tags:["helper_expr","zayn"], explanation:"ביטוי עזר — רק זײַן מוטה. עבר איז געווען שולדיק.", needsReview:false, reviewNote:"" },
    { id:33, sourcePage:84, infinitive:"אויסטראַכטן", presentSentence:"מיר טראַכטן אויס אַ פּאַטענט",
      translation:"אנחנו ממציאים פטנט", past:"מיר האָבן אויסגעטראַכט אַ פּאַטענט",
      future:"מיר וועלן אויסטראַכטן אַ פּאַטענט", imperative:"טראַכט אויס! טראַכט אויס!",
      negative:"מיר טראַכטן נישט אויס קיין פּאַטענט",
      positiveQuestion:"צי טראַכטן מיר אויס אַ פּאַטענט?",
      negativeQuestion:"טראַכטן מיר אויס אַ פּאַטענט?",
      tags:["prefix_split","hobn","no_double_t","nisht_keyn"], explanation:"מתפרק (אויס). מסתיים ב-ט → בלי טט: אויסגעטראַכט.", needsReview:false, reviewNote:"" },
    { id:34, sourcePage:84, infinitive:"ווערן פֿאַרחלשט", presentSentence:"איר ווערט פֿאַרחלשט פֿון דער היץ",
      translation:"אתם נחלשים מהחום", past:"איר זײַט געוואָרן פֿאַרחלשט פֿון דער היץ",
      future:"איר וועט ווערן פֿאַרחלשט פֿון דער היץ", imperative:"ווער פֿאַרחלשט! ווערט פֿאַרחלשט!",
      negative:"איר ווערט נישט פֿאַרחלשט פֿון דער היץ",
      positiveQuestion:"צי ווערט איר פֿאַרחלשט פֿון דער היץ?",
      negativeQuestion:"ווערט איר פֿאַרחלשט פֿון דער היץ?",
      tags:["helper_expr","zayn"], explanation:"ביטוי עזר עם ווערן — רק ווערן מוטה. עבר ווערן→געוואָרן, עזר זײַן.", needsReview:false, reviewNote:"" },
    { id:35, sourcePage:84, infinitive:"אַנטלויפֿן", presentSentence:"זיי אַנטלויפֿן פֿון אַ הונט",
      translation:"הם בורחים מכלב", past:"זיי זײַנען אַנטלאָפֿן פֿון אַ הונט",
      future:"זיי וועלן אַנטלויפֿן פֿון אַ הונט", imperative:"אַנטלויף! אַנטלויפֿט!",
      negative:"זיי אַנטלויפֿן נישט פֿון קיין הונט",
      positiveQuestion:"צי אַנטלויפֿן זיי פֿון אַ הונט?",
      negativeQuestion:"אַנטלויפֿן זיי פֿון אַ הונט?",
      tags:["prefix_fixed","motion","zayn","irregular_past"], explanation:"בלתי מתפרק (אַנט) → בלי גע: אַנטלאָפֿן. תנועה → זײַן.", needsReview:false, reviewNote:"" },
    { id:36, sourcePage:84, infinitive:"דערציילן", presentSentence:"איך דערצייל אַ סך מעשיות",
      translation:"אני מספר הרבה מעשיות", past:"איך האָב דערציילט אַ סך מעשיות",
      future:"איך וועל דערציילן אַ סך מעשיות", imperative:"דערצייל! דערציילט!",
      negative:"איך דערצייל נישט קיין סך מעשיות",
      positiveQuestion:"צי דערצייל איך אַ סך מעשיות?",
      negativeQuestion:"דערצייל איך אַ סך מעשיות?",
      tags:["prefix_fixed","hobn","nisht_keyn"], explanation:"בלתי מתפרק (דער) → בלי גע: דערציילט.", needsReview:false, reviewNote:"" },
    { id:37, sourcePage:84, infinitive:"חלומען", presentSentence:"דו חלומסט פֿאָרן שפּאַצירן אין אמריקה",
      translation:"אתה חולם לנסוע לטייל באמריקה", past:"דו האָסט געחלומט פֿאָרן שפּאַצירן אין אמריקה",
      future:"דו וועסט חלומען פֿאָרן שפּאַצירן אין אמריקה", imperative:"חלום! חלומט!",
      negative:"דו חלומסט נישט פֿאָרן שפּאַצירן אין אמריקה",
      positiveQuestion:"צי חלומסטו פֿאָרן שפּאַצירן אין אמריקה?",
      negativeQuestion:"חלומסטו פֿאָרן שפּאַצירן אין אמריקה?",
      tags:["regular","hobn"], explanation:"רק הפועל הראשון (חלומסט) מוטה — פֿאָרן ושפּאַצירן שמות פועל. עבר געחלומט.", needsReview:false, reviewNote:"" },
    { id:38, sourcePage:84, infinitive:"האָבן ליב", presentSentence:"ער האָט ליב שפּאַצירן בײַם ים אין אָוונט",
      translation:"הוא אוהב לטייל על־יד הים בערב", past:"ער האָט געהאַט ליב שפּאַצירן בײַם ים אין אָוונט",
      future:"ער וועט האָבן ליב שפּאַצירן בײַם ים אין אָוונט", imperative:"האָב ליב! האָט ליב!",
      negative:"ער האָט נישט ליב שפּאַצירן בײַם ים אין אָוונט",
      positiveQuestion:"צי האָט ער ליב שפּאַצירן בײַם ים אין אָוונט?",
      negativeQuestion:"האָט ער ליב שפּאַצירן בײַם ים אין אָוונט?",
      tags:["helper_expr","hobn"], explanation:"ביטוי עזר — רק האָבן מוטה. עבר געהאַט ליב (בדיוק כמו בסיפור 'העץ': ליב געהאַט).", needsReview:false, reviewNote:"" },
    { id:39, sourcePage:84, infinitive:"פסקענען", presentSentence:"זי פסקנט אַ נײַעם געזעץ",
      translation:"היא פוסקת חוק חדש", past:"זי האָט געפסקנט אַ נײַעם געזעץ",
      future:"זי וועט פסקענען אַ נײַעם געזעץ", imperative:"פסקן! פסקנט!",
      negative:"זי פסקנט נישט קיין נײַעם געזעץ",
      positiveQuestion:"צי פסקנט זי אַ נײַעם געזעץ?",
      negativeQuestion:"פסקנט זי אַ נײַעם געזעץ?",
      tags:["regular","hobn","nisht_keyn"], explanation:"רגיל, עבר געפסקנט. אַ נײַעם געזעץ לא מיודע → נישט קיין.", needsReview:false, reviewNote:"" },
    { id:40, sourcePage:84, infinitive:"ווערן דורשטיק", presentSentence:"מיר ווערן דורשטיק נאָך מיטאָג",
      translation:"אנחנו נעשים צמאים אחר הצהריים", past:"מיר זײַנען געוואָרן דורשטיק נאָך מיטאָג",
      future:"מיר וועלן ווערן דורשטיק נאָך מיטאָג", imperative:"ווער דורשטיק! ווערט דורשטיק!",
      negative:"מיר ווערן נישט דורשטיק נאָך מיטאָג",
      positiveQuestion:"צי ווערן מיר דורשטיק נאָך מיטאָג?",
      negativeQuestion:"ווערן מיר דורשטיק נאָך מיטאָג?",
      tags:["helper_expr","zayn"], explanation:"ביטוי עזר עם ווערן. עבר געוואָרן, עזר זײַן.", needsReview:false, reviewNote:"" },
    { id:41, sourcePage:100, infinitive:"ווערן גרויס", presentSentence:"איר ווערט גרויס פֿון טאָג צו טאָג",
      translation:"אתם גדלים מיום ליום", past:"איר זײַט געוואָרן גרויס פֿון טאָג צו טאָג",
      future:"איר וועט ווערן גרויס פֿון טאָג צו טאָג", imperative:"ווער גרויס! ווערט גרויס!",
      negative:"איר ווערט נישט גרויס פֿון טאָג צו טאָג",
      positiveQuestion:"צי ווערט איר גרויס פֿון טאָג צו טאָג?",
      negativeQuestion:"ווערט איר גרויס פֿון טאָג צו טאָג?",
      tags:["helper_expr","zayn"], explanation:"ביטוי עזר עם ווערן+תואר. עבר געוואָרן.", needsReview:false, reviewNote:"" },
    { id:42, sourcePage:100, infinitive:"זײַן מצליח", presentSentence:"די תלמידים זײַנען מצליח אין דעם עקזאַמען",
      translation:"התלמידים מצליחים במבחן", past:"די תלמידים זײַנען געווען מצליח אין דעם עקזאַמען",
      future:"די תלמידים וועלן זײַן מצליח אין דעם עקזאַמען", imperative:"זײַ מצליח! זײַט מצליח!",
      negative:"די תלמידים זײַנען נישט מצליח אין דעם עקזאַמען",
      positiveQuestion:"צי זײַנען די תלמידים מצליח אין דעם עקזאַמען?",
      negativeQuestion:"זײַנען די תלמידים מצליח אין דעם עקזאַמען?",
      tags:["helper_expr","zayn"], explanation:"ביטוי עזר עם זײַן. מיר/זיי זײַנען (ע נכנסת). עבר געווען.", needsReview:false, reviewNote:"" },
    { id:43, sourcePage:100, infinitive:"צעברעכן", presentSentence:"איך צעברעך אַ טעלער צו די תנאים",
      translation:"אני שוברת צלחת לאירוסין", past:"איך האָב צעבראָכן אַ טעלער צו די תנאים",
      future:"איך וועל צעברעכן אַ טעלער צו די תנאים", imperative:"צעברעך! צעברעכט!",
      negative:"איך צעברעך נישט קיין טעלער צו די תנאים",
      positiveQuestion:"צי צעברעך איך אַ טעלער צו די תנאים?",
      negativeQuestion:"צעברעך איך אַ טעלער צו די תנאים?",
      tags:["prefix_fixed","hobn","irregular_past","nisht_keyn"], explanation:"בלתי מתפרק (צע) → בלי גע. עבר חריג: צעבראָכן.", needsReview:false, reviewNote:"" },
    { id:44, sourcePage:100, infinitive:"פֿאַרשרײַבן", presentSentence:"דו פֿאַרשרײַבסט דײַן קינד אין שול",
      translation:"אתה רושם את ילדך לבית הספר", past:"דו האָסט פֿאַרשריבן דײַן קינד אין שול",
      future:"דו וועסט פֿאַרשרײַבן דײַן קינד אין שול", imperative:"פֿאַרשרײַב! פֿאַרשרײַבט!",
      negative:"דו פֿאַרשרײַבסט נישט דײַן קינד אין שול",
      positiveQuestion:"צי פֿאַרשרײַבסטו דײַן קינד אין שול?",
      negativeQuestion:"פֿאַרשרײַבסטו דײַן קינד אין שול?",
      tags:["prefix_fixed","hobn","irregular_past"], explanation:"בלתי מתפרק (פֿאַר) → בלי גע. שורש שרײַבן חריג → פֿאַרשריבן.", needsReview:false, reviewNote:"" },
    { id:45, sourcePage:100, infinitive:"באַקענען", presentSentence:"ער באַקענט נײַע חברים",
      translation:"הוא מכיר חברים חדשים", past:"ער האָט באַקענט נײַע חברים",
      future:"ער וועט באַקענען נײַע חברים", imperative:"באַקען! באַקענט!",
      negative:"ער באַקענט נישט קיין נײַע חברים",
      positiveQuestion:"צי באַקענט ער נײַע חברים?",
      negativeQuestion:"באַקענט ער נײַע חברים?",
      tags:["prefix_fixed","hobn","nisht_keyn"], explanation:"בלתי מתפרק (באַ) → בלי גע: באַקענט.", needsReview:false, reviewNote:"" },
    { id:46, sourcePage:100, infinitive:"שלאָפֿן", presentSentence:"זי שלאָפֿט אין דעם גרויסן צימער",
      translation:"היא ישנה בחדר הגדול", past:"זי איז געשלאָפֿן אין דעם גרויסן צימער",
      future:"זי וועט שלאָפֿן אין דעם גרויסן צימער", imperative:"שלאָף! שלאָפֿט!",
      negative:"זי שלאָפֿט נישט אין דעם גרויסן צימער",
      positiveQuestion:"צי שלאָפֿט זי אין דעם גרויסן צימער?",
      negativeQuestion:"שלאָפֿט זי אין דעם גרויסן צימער?",
      tags:["zayn"], explanation:"פועל פשוט. במקור העבר עם זײַן: זי איז געשלאָפֿן.", needsReview:true, reviewNote:"ERRORS_AND_FIXES מסמן שלאָפֿן עם זײַן כלא-תקני (בד\"כ האָבן: זי האָט געשלאָפֿן). לוודא מול המרצה מה נדרש במבחן." },
    { id:47, sourcePage:100, infinitive:"טאַנצן", presentSentence:"מיר טאַנצן פֿון פֿרייד",
      translation:"אנחנו רוקדים משמחה", past:"מיר האָבן געטאַנצט פֿון פֿרייד",
      future:"מיר וועלן טאַנצן פֿון פֿרייד", imperative:"טאַנץ! טאַנצט!",
      negative:"מיר טאַנצן נישט פֿון פֿרייד",
      positiveQuestion:"צי טאַנצן מיר פֿון פֿרייד?",
      negativeQuestion:"טאַנצן מיר פֿון פֿרייד?",
      tags:["regular","hobn"], explanation:"חריג הפוך: למרות שרוקדים 'עם כל הגוף' — עזר האָבן (עמ' 40). עבר געטאַנצט.", needsReview:false, reviewNote:"" },
    { id:48, sourcePage:100, infinitive:"אַרבעטן", presentSentence:"איר אַרבעט אויף אַ גרויסן פּראָיעקט",
      translation:"אתם עובדים על פרויקט גדול", past:"איר האָט געאַרבעט אויף אַ גרויסן פּראָיעקט",
      future:"איר וועט אַרבעטן אויף אַ גרויסן פּראָיעקט", imperative:"אַרבעט! אַרבעט!",
      negative:"איר אַרבעט נישט אויף קיין גרויסן פּראָיעקט",
      positiveQuestion:"צי אַרבעט איר אויף אַ גרויסן פּראָיעקט?",
      negativeQuestion:"אַרבעט איר אויף אַ גרויסן פּראָיעקט?",
      tags:["regular","hobn","no_double_t","nisht_keyn"], explanation:"מסתיים ב-ט → בלי טט: געאַרבעט. ציווי יחיד=רבים.", needsReview:false, reviewNote:"" },
    { id:49, sourcePage:100, infinitive:"באַאַרבעטן", presentSentence:"זיי באַאַרבעטן דעם גאָרטן",
      translation:"הם מעבדים את הגינה", past:"זיי האָבן באַאַרבעט דעם גאָרטן",
      future:"זיי וועלן באַאַרבעטן דעם גאָרטן", imperative:"באַאַרבעט! באַאַרבעט!",
      negative:"זיי באַאַרבעטן נישט דעם גאָרטן",
      positiveQuestion:"צי באַאַרבעטן זיי דעם גאָרטן?",
      negativeQuestion:"באַאַרבעטן זיי דעם גאָרטן?",
      tags:["prefix_fixed","hobn","no_double_t"], explanation:"בלתי מתפרק (באַ) → בלי גע, ומסתיים ב-ט → בלי טט: באַאַרבעט.", needsReview:false, reviewNote:"" },
    { id:50, sourcePage:100, infinitive:"אַרײַנאַרבעטן", presentSentence:"איך אַרבעט אַרײַן אין דער טעמע",
      translation:"אני משקיע עבודה בנושא הזה", past:"איך האָב אַרײַנגעאַרבעט אין דער טעמע",
      future:"איך וועל אַרײַנאַרבעטן אין דער טעמע", imperative:"אַרבעט אַרײַן! אַרבעט אַרײַן!",
      negative:"איך אַרבעט נישט אַרײַן אין דער טעמע",
      positiveQuestion:"צי אַרבעט איך אַרײַן אין דער טעמע?",
      negativeQuestion:"אַרבעט איך אַרײַן אין דער טעמע?",
      tags:["prefix_split","hobn","no_double_t"], explanation:"מתפרק (אַרײַן). עבר אַרײַנגעאַרבעט (גע באמצע, בלי טט).", needsReview:false, reviewNote:"" },
    { id:51, sourcePage:100, infinitive:"שווימען", presentSentence:"דו שווימסט אין אַ באַסיין",
      translation:"אתה שוחה בבריכה", past:"דו ביסט געשווומען אין אַ באַסיין",
      future:"דו וועסט שווימען אין אַ באַסיין", imperative:"שווים! שווימט!",
      negative:"דו שווימסט נישט אין קיין באַסיין",
      positiveQuestion:"צי שווימסטו אין אַ באַסיין?",
      negativeQuestion:"שווימסטו אין אַ באַסיין?",
      tags:["motion","zayn","irregular_past","nisht_keyn"], explanation:"תנועה → זײַן. עבר עם חילוף פנימי: שווימען → געשווומען.", needsReview:false, reviewNote:"" },
    { id:52, sourcePage:100, infinitive:"קריכן", presentSentence:"ער קריכט אויף גלײַכע ווענט",
      translation:"הוא מטפס על קירות חלקים", past:"ער איז געקראָכן אויף גלײַכע ווענט",
      future:"ער וועט קריכן אויף גלײַכע ווענט", imperative:"קריך! קריכט!",
      negative:"ער קריכט נישט אויף קיין גלײַכע ווענט",
      positiveQuestion:"צי קריכט ער אויף גלײַכע ווענט?",
      negativeQuestion:"קריכט ער אויף גלײַכע ווענט?",
      tags:["motion","zayn","irregular_past","nisht_keyn"], explanation:"תנועה (עם כל הגוף) → זײַן. עבר חריג: געקראָכן.", needsReview:false, reviewNote:"" },
    { id:53, sourcePage:100, infinitive:"אָפּלערנען", presentSentence:"זי לערנט אָפּ די לעקציע אויסנווייניק",
      translation:"היא לומדת את השיעור בעל־פה", past:"זי האָט אָפּגעלערנט די לעקציע אויסנווייניק",
      future:"זי וועט אָפּלערנען די לעקציע אויסנווייניק", imperative:"לערן אָפּ! לערנט אָפּ!",
      negative:"זי לערנט נישט אָפּ די לעקציע אויסנווייניק",
      positiveQuestion:"צי לערנט זי אָפּ די לעקציע אויסנווייניק?",
      negativeQuestion:"לערנט זי אָפּ די לעקציע אויסנווייניק?",
      tags:["prefix_split","hobn"], explanation:"מתפרק (אָפּ). עבר אָפּגעלערנט. 'די לעקציע' מיודע → בלי קיין.", needsReview:false, reviewNote:"" },
    { id:54, sourcePage:100, infinitive:"אויסלייענען", presentSentence:"מיר לייענען אויס די שבתדיקע צײַטונג",
      translation:"אנחנו משלימים את קריאת עיתון השבת", past:"מיר האָבן אויסגעלייענט די שבתדיקע צײַטונג",
      future:"מיר וועלן אויסלייענען די שבתדיקע צײַטונג", imperative:"לייען אויס! לייענט אויס!",
      negative:"מיר לייענען נישט אויס די שבתדיקע צײַטונג",
      positiveQuestion:"צי לייענען מיר אויס די שבתדיקע צײַטונג?",
      negativeQuestion:"לייענען מיר אויס די שבתדיקע צײַטונג?",
      tags:["prefix_split","hobn"], explanation:"מתפרק (אויס). עבר אויסגעלייענט. 'די צײַטונג' מיודע → בלי קיין.", needsReview:false, reviewNote:"" },
    { id:55, sourcePage:100, infinitive:"פֿאַרקוקן זיך", presentSentence:"איר פֿאַרקוקט זיך ווי אין אַ חלום",
      translation:"אתם בוהים כמו בחלום", past:"איר האָט פֿאַרקוקט זיך ווי אין אַ חלום",
      future:"איר וועט פֿאַרקוקן זיך ווי אין אַ חלום", imperative:"פֿאַרקוק זיך! פֿאַרקוקט זיך!",
      negative:"איר פֿאַרקוקט זיך נישט ווי אין קיין חלום",
      positiveQuestion:"צי פֿאַרקוקט איר זיך ווי אין אַ חלום?",
      negativeQuestion:"פֿאַרקוקט איר זיך ווי אין אַ חלום?",
      tags:["prefix_fixed","zikh","hobn"], explanation:"בלתי מתפרק (פֿאַר) + זיך → בלי גע: פֿאַרקוקט. עזר האָבן.", needsReview:false, reviewNote:"" },
    { id:56, sourcePage:100, infinitive:"וואַשן זיך", presentSentence:"זיי וואַשן זיך יעדן טאָג אינדערפֿרי",
      translation:"הם מתרחצים כל יום בבוקר", past:"זיי האָבן געוואַשן זיך יעדן טאָג אינדערפֿרי",
      future:"זיי וועלן וואַשן זיך יעדן טאָג אינדערפֿרי", imperative:"וואַש זיך! וואַשט זיך!",
      negative:"זיי וואַשן זיך נישט יעדן טאָג אינדערפֿרי",
      positiveQuestion:"צי וואַשן זיי זיך יעדן טאָג אינדערפֿרי?",
      negativeQuestion:"וואַשן זיי זיך יעדן טאָג אינדערפֿרי?",
      tags:["zikh","hobn"], explanation:"פועל חוזר (זיך). עזר האָבן, עבר געוואַשן.", needsReview:true, reviewNote:"סדר ה-זיך בעבר: המקור כותב 'האָבן געוואַשן זיך' (זיך אחרי הבינוני), אך ERRORS מציין גם 'האָבן זיך געוואַשן'. לוודא מול המרצה איזה סדר נדרש." },
    { id:57, sourcePage:100, infinitive:"באַקענען זיך", presentSentence:"איך באַקען זיך מיט נײַע חברים",
      translation:"אני עורך היכרות עם חברים חדשים", past:"איך האָב באַקענט זיך מיט נײַע חברים",
      future:"איך וועל באַקענען זיך מיט נײַע חברים", imperative:"באַקען זיך! באַקענט זיך!",
      negative:"איך באַקען זיך נישט מיט קיין נײַע חברים",
      positiveQuestion:"צי באַקען איך זיך מיט נײַע חברים?",
      negativeQuestion:"באַקען איך זיך מיט נײַע חברים?",
      tags:["prefix_fixed","zikh","hobn","nisht_keyn"], explanation:"בלתי מתפרק (באַ) + זיך → בלי גע: באַקענט.", needsReview:true, reviewNote:"סדר ה-זיך בעבר כמו במשפט 56 ('באַקענט זיך'). לוודא מול המרצה." },
    { id:58, sourcePage:100, infinitive:"פֿאַרשרײַבן זיך", presentSentence:"דו פֿאַרשרײַבסט זיך אין אַ ספּאָרט קלוב",
      translation:"אתה נרשם למועדון ספורט", past:"דו האָסט פֿאַרשריבן זיך אין אַ ספּאָרט קלוב",
      future:"דו וועסט פֿאַרשרײַבן זיך אין אַ ספּאָרט קלוב", imperative:"פֿאַרשרײַב זיך! פֿאַרשרײַבט זיך!",
      negative:"דו פֿאַרשרײַבסט זיך נישט אין קיין ספּאָרט קלוב",
      positiveQuestion:"צי פֿאַרשרײַבסטו זיך אין אַ ספּאָרט קלוב?",
      negativeQuestion:"פֿאַרשרײַבסטו זיך אין אַ ספּאָרט קלוב?",
      tags:["prefix_fixed","zikh","hobn","irregular_past","nisht_keyn"], explanation:"בלתי מתפרק (פֿאַר) + זיך → בלי גע. שורש שרײַבן חריג → פֿאַרשריבן.", needsReview:true, reviewNote:"סדר ה-זיך בעבר ('פֿאַרשריבן זיך'). לוודא מול המרצה." },
    { id:59, sourcePage:100, infinitive:"ברענגען", presentSentence:"זיי ברענגען בלומען אויף שבת",
      translation:"הם מביאים פרחים לשבת", past:"זיי האָבן געברענגט בלומען אויף שבת",
      future:"זיי וועלן ברענגען בלומען אויף שבת", imperative:"ברענג! ברענגט!",
      negative:"זיי ברענגען נישט קיין בלומען אויף שבת",
      positiveQuestion:"צי ברענגען זיי בלומען אויף שבת?",
      negativeQuestion:"ברענגען זיי בלומען אויף שבת?",
      tags:["hobn","irregular_past","nisht_keyn"], explanation:"עבר עם האָבן. בלומען לא מיודע → נישט קיין.", needsReview:true, reviewNote:"שתי צורות עבר תקינות לפי המקור: געברענגט = געבראַכט. שתיהן מתקבלות." },
    { id:60, sourcePage:100, infinitive:"וווינען", presentSentence:"די קינדער וווינען אין שטאָט",
      translation:"הילדים גרים בעיר", past:"די קינדער האָבן געוווינט אין שטאָט",
      future:"די קינדער וועלן וווינען אין שטאָט", imperative:"וווין! וווינט!",
      negative:"די קינדער וווינען נישט אין שטאָט",
      positiveQuestion:"צי וווינען די קינדער אין שטאָט?",
      negativeQuestion:"וווינען די קינדער אין שטאָט?",
      tags:["regular","hobn"], explanation:"חריג הפוך: לגור נשאר עם האָבן (עמ' 40). עבר געוווינט.", needsReview:false, reviewNote:"" }
  ],

  STORIES: [
    { id:"pekele_puter", titleYiddish:"דאָס פּעקעלע פּוטער", titleHebrew:"חבילת החמאה (וואָלאַדקע)",
      subtitle:"יום הזיכרון לשואה ולגבורה — עמ' 150–151",
      summaryHebrew:"הגרמנים כבשו את ורשה, גירשו את היהודים לגטו מוקף חומה ושמרו עליו עם רובים. בגטו שררו רעב ומחלות, והנאצים שילחו יהודים למחנות והרגו בגז. הצעירים הגיבורים החליטו למרוד ונזקקו לנשק מבחוץ. וולאדקה, שלא נראתה יהודייה, נשארה מחוץ לחומה כדי לעזור. היא הבריחה לגטו דינמיט ארוז כמו חבילת חמאה: ישבה על החומה, נשמעו יריות, חבר קרא לה 'וואָלאַדקע, שנעלער!', היא החליקה פנימה, ברחה איתו, ומסרה את הדינמיט לחברים.",
      vocabulary:[
        {yi:"די נאַציס",he:"הנאצים"},{yi:"דאָס געטאָ",he:"הגטו"},{yi:"די מויער",he:"החומה"},
        {yi:"ביקסן",he:"רובים"},{yi:"דינאַמיט",he:"דינמיט"},{yi:"דאָס פּעקעלע פּוטער",he:"חבילת החמאה"},
        {yi:"אויפֿשטאַנד",he:"מרד"},{yi:"סכּנה",he:"סכנה"},{yi:"העלדיש",he:"גיבור"},{yi:"דערלויבעניש",he:"רשות"}
      ],
      questions:[
        {id:1, questionYiddish:"ווער זײַנען געווען די נאַציס?", modelAnswerYiddish:"די נאַציס זײַנען געווען דײַטשן מיט ביקסן.", note:"הנאצים היו גרמנים עם רובים."},
        {id:2, questionYiddish:"וואָס איז אַ געטאָ?", modelAnswerYiddish:"אַ געטאָ איז אַ קליינער צאָל גאַסן מיט אַ מויער.", note:"גטו = מספר קטן של רחובות עם חומה."},
        {id:3, questionYiddish:"וואָס האָבן די נאַציס געטאָן די ייִדן פֿון געטאָ?", modelAnswerYiddish:"די נאַציס האָבן די ייִדן פֿון געטאָ פֿאַרגאַזט און פֿאַרברענט.", note:"הרגו בגז ושרפו את יהודי הגטו."},
        {id:4, questionYiddish:"צוליב וואָס איז וואָלאַדקע געבליבן אויף יענער זײַט מויער?", modelAnswerYiddish:"וואָלאַדקע איז געבליבן אויף יענער זײַט מויער כּדי צו העלפֿן.", note:"נשארה בצד השני כדי לעזור — לא נראתה יהודייה."},
        {id:5, questionYiddish:"ווען האָבן די יונגע העלדישע באַשלאָסן צו מאַכן אַן אויפֿשטאַנד?", modelAnswerYiddish:"די יונגע העלדישע ייִדן האָבן באַשלאָסן צו מאַכן אַן אויפֿשטאַנד ווען עס זײַנען שוין געבליבן ווייניק ייִדן אין געטאָ.", note:"כשנשארו מעט יהודים בגטו."},
        {id:6, questionYiddish:"ווי אַזוי האָט וואָלאַדקע געטראָגן דינאַמיט אין געטאָ?", modelAnswerYiddish:"וואָלאַדקע האָט געטראָגן דינאַמיט אין געטאָ אין אַ פּעקעלע פּוטער.", note:"בתוך חבילה שנראתה כמו חבילת חמאה."},
        {id:7, questionYiddish:"וואָס איז געשען ווען וואָלאַדקע איז געווען אויף דער מויער פֿון געטאָ?", modelAnswerYiddish:"ווען וואָלאַדקע איז געווען אויף דער מויער פֿון געטאָ, האָבן זיך דערהערט שאָסן.", note:"נשמעו יריות; החברים ברחו והיא נשארה לבד."},
        {id:8, questionYiddish:"וואָס איז געווען די סכּנה בײַם אַראָפּשפּרינגען פֿון געטאָ מויער?", modelAnswerYiddish:"די סכּנה איז געווען אַז זי קען נאָך פֿאַלן און דאָס פּעקעלע פּוטער קען אויפֿרײַסן.", note:"שתיפול והחבילה תתפוצץ, או שהנאצים יראו אותה ויירו. שתי גרסאות מהמורה — שתיהן טובות."}
      ]
    },
    { id:"shisele_boiml", titleYiddish:"דאָס שיסעלע מיט בוימל", titleHebrew:"הקערית עם השמן",
      subtitle:"חנוכה — עמ' 131–134",
      summaryHebrew:"בכל לילה של חורף דולקת קערית שמן על חלון ביתו של אברהם, בקצה הכפר. כשילדיו שאלו למה, סיפר: לפני כ-20 שנה, בגיל 19, הוריו מתו והוא נשאר לבד בלי מקצוע. ביום חורף פרצה סופת שלגים; הוא נפל בשלג. מחשבה אחת דחקה בו לקום, השנייה פיתתה לישון. ואז ראה מרחוק אור קטן שיצא מבית, נגרר אליו והתעלף בפתח. זקן, זקנה ונערה טיפלו בו שבועיים. הזקן סיפר שאותו לילה היה ליל חנוכה הראשון, והאור היה נר החנוכה. הזקן הציע לו להישאר, הוא התחתן עם בתם. מאז כל חורף הוא מדליק את קערית השמן על החלון — כדי שמאחרים בדרכים לא יאבדו בשלג.",
      vocabulary:[
        {yi:"דאָס שיסעלע",he:"הקערית"},{yi:"בוימל",he:"שמן"},{yi:"דאָס פֿענצטערל",he:"החלון הקטן"},
        {yi:"דער באַלעבאָס",he:"בעל הבית"},{yi:"שנייסטורעם",he:"סופת שלגים"},{yi:"דער געדאַנק",he:"המחשבה/הרעיון"},
        {yi:"אַ פֿײַערל",he:"אור/אש קטנה"},{yi:"חנוכּה-ליכטל",he:"נר חנוכה"},{yi:"פֿאַרחלשט",he:"מעולף"},{yi:"עק דאָרף",he:"קצה הכפר"}
      ],
      questions:[
        {id:1, questionYiddish:"ווו שטייט דאָס הייזל?", modelAnswerYiddish:"דאָס הייזל שטייט בײַם עק דאָרף.", note:"הבית עומד בקצה הכפר."},
        {id:2, questionYiddish:"פֿאַרוואָס ווונדערן זיך די מענטשן?", modelAnswerYiddish:"די מענטשן ווונדערן זיך וואָס, ווי נאָר עס קומט דער ווינטער, אַזוי שטעלט אַוועק דער באַלעבאָס יעדן אויף דער נאַכט דאָס שיסעלע מיט בוימל אויפֿן פֿענצטער.", note:"מתפלאים שברגע שמגיע החורף בעל הבית מעמיד כל לילה את קערית השמן על החלון."},
        {id:3, questionYiddish:"ווי אַזוי האָט געהייסן דער בעל-הבית?", modelAnswerYiddish:"דער באַלעבאָס האָט געהייסן אברהם.", note:"קראו לו אברהם."},
        {id:4, questionYiddish:"ווען איז די מעשׂה געווען?", modelAnswerYiddish:"די מעשׂה איז געווען מיט אַ צוואַנציק יאָר צוריק.", note:"לפני כעשרים שנה — כשאברהם היה בן 19."},
        {id:5, questionYiddish:"וואָס האָט געזאָגט דער ערשטער געדאַנק?", modelAnswerYiddish:"דער ערשטער געדאַנק האָט געזאָגט: וואָס טוסטו? דרעמל ניט אײַן!", note:"המחשבה הראשונה: מה אתה עושה? אל תירדם!"},
        {id:6, questionYiddish:"וואָס האָט ער דערזען אין חלום?", modelAnswerYiddish:"ער האָט דערזען אין חלום אַ פֿײַערל.", note:"ראה אור/אש קטנה."},
        {id:7, questionYiddish:"וואָס האָט דער אַלטער געזאָגט?", modelAnswerYiddish:"דער אַלטער האָט געזאָגט: אויב דו, בחור, האָסט ליב אַרבעט, קענסטו בײַ מיר דאָ פֿאַרבלײַבן.", note:"אם אתה אוהב עבודה, תוכל להישאר כאן אצלי."},
        {id:8, questionYiddish:"וואָס טוט ער יעדן ווינטער?", modelAnswerYiddish:"יעדן ווינטער צינדט ער אָן אַ שיסעלע מיט בוימל.", note:"כל חורף מדליק קערית שמן — כדי להציל מאחרים בדרכים."}
      ]
    },
    { id:"boim_yingl", titleYiddish:"דער בוים און דאָס יינגל", titleHebrew:"העץ והילד (העץ הנדיב)",
      subtitle:"עמ' 138–140",
      summaryHebrew:"היה עץ שאהב ילד קטן. הילד בא כל יום: אסף עלים ועשה מהם כתרים, טיפס על הגזע, אכל תפוחים, שיחקו במחבואים וישן בצל. שניהם היו מאושרים. הילד גדל: ביקש כסף — העץ נתן תפוחים למכור בשוק; ביקש בית לאישה וילדים — נתן את ענפיו; ביקש ספינה להפליג — נתן את גזעו. הילד נעלם זמן רב והעץ היה עצוב. בסוף חזר זקן ועייף וביקש רק מקום לשבת — העץ הציע את הגדם, והילד נח. העץ היה מאושר: נתן הכול.",
      vocabulary:[
        {yi:"דער בוים",he:"העץ"},{yi:"דאָס יינגל",he:"הילד"},{yi:"די בלעטער",he:"העלים"},
        {yi:"די עפּל",he:"התפוחים"},{yi:"די צווײַגן",he:"הענפים"},{yi:"דער שטאַם",he:"הגזע"},
        {yi:"אַ שיף",he:"ספינה"},{yi:"אַ הויז",he:"בית"},{yi:"באַהעלטעניש",he:"מחבואים"},
        {yi:"טרויעריק",he:"עצוב"},{yi:"גליקלעך",he:"מאושר"},{yi:"דער שאָטן",he:"הצל"}
      ],
      questions:[
        {id:1, questionYiddish:"וועמען האָט דער בוים ליב געהאַט?", modelAnswerYiddish:"דער בוים האָט ליב געהאַט דאָס יינגל.", note:"העץ אהב את הילד. (ליב געהאַט = עבר של האָבן ליב.)"},
        {id:2, questionYiddish:"וואָס האָט דאָס יינגל געזאַמלט?", modelAnswerYiddish:"דאָס יינגל האָט געזאַמלט די בלעטער.", note:"הילד אסף את העלים ועשה מהם כתרים."},
        {id:3, questionYiddish:"אין וואָס האָבן זיי זיך געשפּילט?", modelAnswerYiddish:"זיי האָבן זיך געשפּילט אין באַהעלטעניש.", note:"שיחקו במחבואים. (זיך געשפּילט = פועל עם זיך בעבר.)"},
        {id:4, questionYiddish:"וואָס האָט דער בוים געגעבן?", modelAnswerYiddish:"דער בוים האָט געגעבן זײַן פֿרוכט / אַלץ וואָס ער קען.", note:"נתן פירותיו / כל מה שיכול: תפוחים, ענפים, גזע, ובסוף גדם."},
        {id:5, questionYiddish:"פֿאַרוואָס האָט דאָס יינגל געוואָלט אַ שיף?", modelAnswerYiddish:"דאָס יינגל האָט געוואָלט אַ שיף כּדי אַוועקצופֿאָרן.", note:"רצה ספינה כדי להפליג רחוק."},
        {id:6, questionYiddish:"וואָס האָט דאָס יינגל געטאָן מיט די עפּל?", modelAnswerYiddish:"דאָס יינגל האָט גענומען די עפּל אין מאַרק פֿאַרקויפֿן.", note:"לקח את התפוחים למכור בשוק."},
        {id:7, questionYiddish:"פֿאַרוואָס איז דער בוים געווען טרויעריק?", modelAnswerYiddish:"דער בוים איז געווען טרויעריק ווײַל דאָס יינגל איז ניט צוריקגעקומען אַ לאַנגע צײַט.", note:"העץ היה עצוב כי הילד לא חזר זמן רב."},
        {id:8, questionYiddish:"פֿאַרוואָס האָט דאָס יינגל געוואָלט אַ הויז?", modelAnswerYiddish:"דאָס יינגל האָט געוואָלט אַ הויז: איך וויל אַ ווײַב און קינדער.", note:"רצה בית כי רצה אישה וילדים."}
      ]
    }
  ],

  FILL_IN_BANK: [
    // A. התאמת כינוי גוף לצורת הפועל (לערנען)
    { id:1, type:"pronoun_verb", prompt:"איך ______", options:["לערן","לערנסט","לערנט","לערנען"], correctAnswer:"לערן", explanation:"איך → סיומת ø: לערן.", tags:["pronoun","present_conjugation"] },
    { id:2, type:"pronoun_verb", prompt:"דו ______", options:["לערן","לערנסט","לערנט","לערנען"], correctAnswer:"לערנסט", explanation:"דו → סיומת סט: לערנסט.", tags:["pronoun","present_conjugation"] },
    { id:3, type:"pronoun_verb", prompt:"ער ______", options:["לערן","לערנסט","לערנט","לערנען"], correctAnswer:"לערנט", explanation:"ער/זי/עס → סיומת ט: לערנט.", tags:["pronoun","present_conjugation"] },
    { id:4, type:"pronoun_verb", prompt:"מיר ______", options:["לערן","לערנסט","לערנט","לערנען"], correctAnswer:"לערנען", explanation:"מיר → צורת המקור: לערנען.", tags:["pronoun","present_conjugation"] },
    { id:5, type:"pronoun_verb", prompt:"זיי ______", options:["לערן","לערנסט","לערנט","לערנען"], correctAnswer:"לערנען", explanation:"זיי → צורת המקור: לערנען.", tags:["pronoun","present_conjugation"] },
    // B. שיבוץ צורת הפועל הנכונה (גיין)
    { id:6, type:"verb_form", prompt:"איך ______ אַהיים.", options:["גיי","גייסט","גייט","גייען"], correctAnswer:"גיי", explanation:"איך → גיי.", tags:["present_conjugation"] },
    { id:7, type:"verb_form", prompt:"דו ______ אין שול.", options:["גיי","גייסט","גייט","גייען"], correctAnswer:"גייסט", explanation:"דו → גייסט.", tags:["present_conjugation"] },
    { id:8, type:"verb_form", prompt:"ער ______ מיט די קינדער.", options:["גיי","גייסט","גייט","גייען"], correctAnswer:"גייט", explanation:"ער → גייט.", tags:["present_conjugation"] },
    { id:9, type:"verb_form", prompt:"מיר ______ אין פּאַרק.", options:["גיי","גייסט","גייט","גייען"], correctAnswer:"גייען", explanation:"מיר → גייען (גיין חריג: מיר/זיי גייען).", tags:["present_conjugation"] },
    { id:10, type:"verb_form", prompt:"זיי ______ צו דער חתונה.", options:["גיי","גייסט","גייט","גייען"], correctAnswer:"גייען", explanation:"זיי → גייען.", tags:["present_conjugation"] },
    // C. מילות יחס
    { id:11, type:"preposition", prompt:"איך רעד ______ חברים אין פּאַרק.", options:["מיט","פֿון","צו","אויף","אין","בײַ"], correctAnswer:"מיט", explanation:"לדבר עם → מיט.", tags:["preposition"] },
    { id:12, type:"preposition", prompt:"דאָס בוך ליגט ______ דעם טיש.", options:["מיט","פֿון","צו","אויף","אין","בײַ"], correctAnswer:"אויף", explanation:"מונח על → אויף.", tags:["preposition"] },
    { id:13, type:"preposition", prompt:"זי וווינט ______ שטאָט.", options:["מיט","פֿון","צו","אויף","אין","בײַ"], correctAnswer:"אין", explanation:"גרה ב־ → אין.", tags:["preposition"] },
    { id:14, type:"preposition", prompt:"ער קומט ______ די שכנים.", options:["מיט","פֿון","צו","אויף","אין","בײַ"], correctAnswer:"צו", explanation:"בא אל → צו.", tags:["preposition"] },
    { id:15, type:"preposition", prompt:"דאָס פֿייגעלע פֿליט ______ מײַן פֿענצטער.", options:["מיט","פֿון","צו","אויף","אין","בײַ"], correctAnswer:"בײַ", explanation:"על־יד → בײַ.", tags:["preposition"] },
    // D. מילות שאלה
    { id:16, type:"question_word", prompt:"______ לערנסטו? — איך לערן אין אוניווערסיטעט.", options:["וואָס","ווער","ווו","ווען","פֿאַרוואָס","וויפֿל"], correctAnswer:"ווו", explanation:"התשובה מקום (אוניברסיטה) → ווו (איפה).", tags:["question_word"] },
    { id:17, type:"question_word", prompt:"______ קינדער האָסטו? — איך האָב דרײַ קינדער.", options:["וואָס","ווער","ווו","ווען","פֿאַרוואָס","וויפֿל"], correctAnswer:"וויפֿל", explanation:"התשובה כמות (שלושה) → וויפֿל (כמה).", tags:["question_word"] },
    { id:18, type:"question_word", prompt:"______ איז דאָס? — דאָס איז מײַן חבר.", options:["וואָס","ווער","ווו","ווען","פֿאַרוואָס","וויפֿל"], correctAnswer:"ווער", explanation:"התשובה אדם (חבר) → ווער (מי).", tags:["question_word"] },
    { id:19, type:"question_word", prompt:"______ קומסטו אַהיים? — איך קום אין אָוונט.", options:["וואָס","ווער","ווו","ווען","פֿאַרוואָס","וויפֿל"], correctAnswer:"ווען", explanation:"התשובה זמן (בערב) → ווען (מתי).", tags:["question_word"] },
    { id:20, type:"question_word", prompt:"______ ביסטו טרויעריק? — ווײַל מײַן חבר איז אַוועק.", options:["וואָס","ווער","ווו","ווען","פֿאַרוואָס","וויפֿל"], correctAnswer:"פֿאַרוואָס", explanation:"התשובה סיבה (כי) → פֿאַרוואָס (למה).", tags:["question_word"] },
    // E. נישט / נישט קיין
    { id:21, type:"nisht_keyn", prompt:"ער שרײַבט ______ בריוו. (במקור: אַ בריוו)", options:["נישט","נישט קיין"], correctAnswer:"נישט קיין", explanation:"אַ בריוו לא מיודע → נישט קיין.", tags:["negation"] },
    { id:22, type:"nisht_keyn", prompt:"איך רעד ______ מיט דעם חבר. (במקור: מיט דעם חבר)", options:["נישט","נישט קיין"], correctAnswer:"נישט", explanation:"'דעם חבר' מיודע → רק נישט.", tags:["negation"] },
    { id:23, type:"nisht_keyn", prompt:"מיר האָבן ______ דרײַ קינדער. (במקור: דרײַ קינדער)", options:["נישט","נישט קיין"], correctAnswer:"נישט קיין", explanation:"מספר (דרײַ) → נישט קיין.", tags:["negation"] },
    { id:24, type:"nisht_keyn", prompt:"זי איז ______ די שענסטע אין קלאַס. (במקור: די שענסטע)", options:["נישט","נישט קיין"], correctAnswer:"נישט", explanation:"'די שענסטע' מיודע → רק נישט.", tags:["negation"] },
    { id:25, type:"nisht_keyn", prompt:"דער חבר לייענט ______ אַרטיקל. (במקור: אַן אַרטיקל)", options:["נישט","נישט קיין"], correctAnswer:"נישט קיין", explanation:"אַן אַרטיקל לא מיודע → נישט קיין.", tags:["negation"] }
  ]
};
